<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Mediator.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="WTorricos.Results" />
        <PackageReference Include="ZXing.Net" />
        <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" />
    </ItemGroup>

</Project>
