<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Receipts.Contracts\Receipts.Contracts.csproj" />
      <ProjectReference Include="..\Reports.Contracts\Reports.Contracts.csproj" />
    </ItemGroup>

</Project>
