<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <PublishTrimmed>false</PublishTrimmed>
    </PropertyGroup>

<!--    <PropertyGroup>-->
<!--        <WasmBuildNative>true</WasmBuildNative>-->
<!--    </PropertyGroup>-->
    <ItemGroup>
        <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\*.a" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
        <PackageReference Include="Microsoft.DotNet.HotReload.WebAssembly.Browser" />
        <PackageReference Include="Microsoft.NET.Sdk.WebAssembly.Pack" />
        <PackageReference Include="MudBlazor" />
        <PackageReference Include="Refit" />
        <PackageReference Include="Refit.HttpClientFactory" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BlazorConsolidated\BlazorConsolidated.csproj" />
    </ItemGroup>

</Project>
