<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ClientServerContracts\ClientServerContracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.0.0" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
      <PackageReference Include="SkiaSharp" Version="3.119.1" />
      <PackageReference Include="WTorricos.Results" Version="2.0.4" />
      <PackageReference Include="ZXing.Net" Version="0.16.10" />
      <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.21" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="MediatorWithResults\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="MediatorWithResults\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="MediatorWithResults\**" />
    </ItemGroup>

</Project>
