<Project>
<!--  <PropertyGroup>-->
<!--    &lt;!&ndash; Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management &ndash;&gt;-->
<!--    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>-->
<!--  </PropertyGroup>-->
<!--  <ItemGroup>-->
<!--  </ItemGroup>-->
</Project>
