services:
  docker-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "11111:11111"
    expose:
      - "18888"
      - "18889"
      - "11111"
    networks:
      - "aspire"
    restart: "always"
  db:
    image: "docker.io/library/postgres:17.5"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${USERNAME}"
      POSTGRES_PASSWORD: "${PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "apphost-feed4158f1-db-data"
        read_only: false
    networks:
      - "aspire"
    healthcheck:
      test: ["CMD", "pg_isready", "-U ${USERNAME}", "-d HomeAccounting"]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "20s"
  api:
    build:
      context: .
      dockerfile: ./Api/Dockerfile
    image: ghcr.io/alexey020602/homeaccounting-web:latest
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_PORT}"
      ConnectionStrings__HomeAccounting: "Host=db;Port=5432;Username=${USERNAME};Password=${PASSWORD};Database=HomeAccounting"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://docker-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api"
    ports:
      - "${API_PORT}"
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  apphost-feed4158f1-db-data:
    driver: "local"
