services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: reverse-proxy
    restart: always
    networks:
      - my-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  conf:
    driver: local
  vhost:
    driver: local
  certs:
    driver: local
  acme:
    driver: local
  html:
    driver: local

networks:
  default:
    name: my-network