<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.0"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>3547452e-7082-40b7-ab7a-c7c0613595f9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.0" />
        <PackageReference Include="Aspire.Hosting.Docker" Version="13.1.0-preview.1.25616.3" />
        <PackageReference Include="Aspire.Hosting.Kubernetes" Version="13.1.0-preview.1.25616.3" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.0" />
        <PackageReference Include="Aspire.Hosting.Yarp" Version="13.1.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.2" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Client\Client.csproj"/>
        <ProjectReference Include="..\Api\Api.csproj"/>
        <ProjectReference Include="..\MyBudgets\MyBudgets.csproj" />
    </ItemGroup>

</Project>
