// <auto-generated />
using System;
using HomeAccounting.Budgets.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeAccounting.Budgets.Data.Database.Migrations
{
    [DbContext(typeof(BudgetsContext))]
    [Migration("20260202090225_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("budgets")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("BudgetRoleSequence", "budgets")
                .IncrementsBy(10);

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BeginOfPeriod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Limit")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Budgets", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.BudgetRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "BudgetRoleSequence", "budgets");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BudgetRoles", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.BudgetUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<int>("BudgetRoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BudgetId");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetUser", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Spending", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Spending", "budgets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Spending");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.ManualSpending", b =>
                {
                    b.HasBaseType("HomeAccounting.Budgets.Data.Spending");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Sum")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("ManualSpending");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.ReceiptSpending", b =>
                {
                    b.HasBaseType("HomeAccounting.Budgets.Data.Spending");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeclaredSum")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchasePlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("ReceiptSpending");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.BudgetUser", b =>
                {
                    b.HasOne("HomeAccounting.Budgets.Data.Budget", null)
                        .WithMany("BudgetUsers")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Spending", b =>
                {
                    b.HasOne("HomeAccounting.Budgets.Data.Budget", null)
                        .WithMany("Spendings")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.ReceiptSpending", b =>
                {
                    b.OwnsMany("HomeAccounting.Budgets.Data.Product", "Products", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<long>("Price")
                                .HasColumnType("bigint");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<Guid>("ReceiptSpendingId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Sum")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("CategoryId");

                            b1.HasIndex("ReceiptSpendingId");

                            b1.ToTable("Product", "budgets");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptSpendingId");
                        });

                    b.OwnsMany("HomeAccounting.Budgets.Data.ReceiptProcessingAttempt", "Attempts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<DateTime>("AttemptedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ErrorMessage")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<bool>("IsSuccess")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("ReceiptSpendingId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ReceiptSpendingId");

                            b1.ToTable("ReceiptProcessingAttempt", "budgets");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptSpendingId");
                        });

                    b.OwnsOne("HomeAccounting.Common.Model.ReceiptFiscalData", "FiscalData", b1 =>
                        {
                            b1.Property<Guid>("ReceiptSpendingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Fd")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fd");

                            b1.Property<string>("Fn")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fn");

                            b1.Property<string>("Fp")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fp");

                            b1.HasKey("ReceiptSpendingId");

                            b1.HasIndex("Fd", "Fn", "Fp")
                                .IsUnique();

                            b1.ToTable("Spending", "budgets");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptSpendingId");
                        });

                    b.Navigation("Attempts");

                    b.Navigation("FiscalData")
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Budget", b =>
                {
                    b.Navigation("BudgetUsers");

                    b.Navigation("Spendings");
                });
#pragma warning restore 612, 618
        }
    }
}
