// <auto-generated />
using System;
using HomeAccounting.Budgets.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeAccounting.Budgets.Data.Database.Migrations
{
    [DbContext(typeof(BudgetsContext))]
    partial class BudgetsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("budgets")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("BudgetRoleSequence", "budgets")
                .IncrementsBy(10);

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BeginOfPeriod")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Limit")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Budgets", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.BudgetRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "BudgetRoleSequence", "budgets");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BudgetRoles", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.BudgetUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<int>("BudgetRoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BudgetId");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetUser", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Sum")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Operation", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PurchasePlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Receipts", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.ReceiptProcessingOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.HasIndex("Status", "NextRetryAt");

                    b.ToTable("ReceiptProcessingOutboxEntry", "budgets");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.BudgetUser", b =>
                {
                    b.HasOne("HomeAccounting.Budgets.Data.Budget", null)
                        .WithMany("BudgetUsers")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Operation", b =>
                {
                    b.HasOne("HomeAccounting.Budgets.Data.Budget", null)
                        .WithMany("Operations")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Receipt", b =>
                {
                    b.OwnsMany("HomeAccounting.Budgets.Data.Product", "Products", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<int?>("CategoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<long>("Price")
                                .HasColumnType("bigint");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Sum")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("CategoryId");

                            b1.HasIndex("ReceiptId");

                            b1.ToTable("Product", "budgets");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId");
                        });

                    b.OwnsOne("HomeAccounting.Common.Model.ReceiptFiscalData", "FiscalData", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Fd")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fd");

                            b1.Property<string>("Fn")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fn");

                            b1.Property<string>("Fp")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fp");

                            b1.Property<DateTimeOffset>("PurchaseDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PurchaseDate");

                            b1.Property<long>("Sum")
                                .HasColumnType("bigint")
                                .HasColumnName("Sum");

                            b1.HasKey("ReceiptId");

                            b1.HasIndex("Fd", "Fn", "Fp");

                            b1.ToTable("Receipts", "budgets");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId");
                        });

                    b.Navigation("FiscalData")
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("HomeAccounting.Budgets.Data.Budget", b =>
                {
                    b.Navigation("BudgetUsers");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
