// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudgets.Budgets.Data.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyBudgets.Budgets.Data.Database.Migrations
{
    [DbContext(typeof(BudgetsContext))]
    [Migration("20260115192648_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("budgets")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("BudgetRoleSequence", "budgets")
                .IncrementsBy(10);

            modelBuilder.HasSequence("CategoriesSequence")
                .IncrementsBy(10);

            modelBuilder.HasSequence("ProductsSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("MyBudgets.Budgets.Data.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BeginOfPeriod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Limit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Budgets", "budgets");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.BudgetRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "BudgetRoleSequence", "budgets");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BudgetRoles", "budgets");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.BudgetUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<int>("BudgetRoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "BudgetId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("BudgetRoleId");

                    b.ToTable("BudgetUsers", "budgets");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "CategoriesSequence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories", "budgets");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "ProductsSequence");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ReceiptSpendingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptSpendingId");

                    b.ToTable("Product", "budgets");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.Spending", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("Spendings", "budgets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Spending");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyBudgets.Users.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", "budgets");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.ManualSpending", b =>
                {
                    b.HasBaseType("MyBudgets.Budgets.Data.Spending");

                    b.HasDiscriminator().HasValue("ManualSpending");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.ReceiptSpending", b =>
                {
                    b.HasBaseType("MyBudgets.Budgets.Data.Spending");

                    b.Property<string>("PurchasePlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("ReceiptSpending");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.BudgetUser", b =>
                {
                    b.HasOne("MyBudgets.Budgets.Data.Budget", null)
                        .WithMany("BudgetUsers")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBudgets.Budgets.Data.BudgetRole", null)
                        .WithMany("BudgetUsers")
                        .HasForeignKey("BudgetRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.Product", b =>
                {
                    b.HasOne("MyBudgets.Budgets.Data.ReceiptSpending", null)
                        .WithMany("Products")
                        .HasForeignKey("ReceiptSpendingId");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.Spending", b =>
                {
                    b.HasOne("MyBudgets.Budgets.Data.Budget", null)
                        .WithMany("Spendings")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudgets.Users.Data.User", b =>
                {
                    b.OwnsOne("MyBudgets.Users.Data.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("User", "budgets");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.ReceiptSpending", b =>
                {
                    b.OwnsOne("MyBudgets.Budgets.Data.ReceiptFiscalData", "FiscalData", b1 =>
                        {
                            b1.Property<Guid>("ReceiptSpendingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Fd")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fd");

                            b1.Property<string>("Fn")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fn");

                            b1.Property<string>("Fp")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Fp");

                            b1.HasKey("ReceiptSpendingId");

                            b1.ToTable("Spendings", "budgets");

                            b1.WithOwner()
                                .HasForeignKey("ReceiptSpendingId");
                        });

                    b.Navigation("FiscalData")
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.Budget", b =>
                {
                    b.Navigation("BudgetUsers");

                    b.Navigation("Spendings");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.BudgetRole", b =>
                {
                    b.Navigation("BudgetUsers");
                });

            modelBuilder.Entity("MyBudgets.Budgets.Data.ReceiptSpending", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
