<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Checks.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc" />
      <PackageReference Include="Scrutor" />
      <PackageReference Include="SkiaSharp" />
      <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Receipts.Core\Receipts.Core.csproj" />
      <ProjectReference Include="..\Receipts.DataBase\Receipts.DataBase.csproj" />
      <ProjectReference Include="..\Shared.Infrastructure\Shared.Infrastructure.csproj" />
      <ProjectReference Include="..\Shared.Web\Shared.Web.csproj" />
    </ItemGroup>

</Project>
