<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Budgets.DataBase\Budgets.DataBase.csproj" />
      <ProjectReference Include="..\Shared.Infrastructure\Shared.Infrastructure.csproj" />
      <ProjectReference Include="..\Shared.Web\Shared.Web.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
