apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-webhook
    receivers:
      - uid: default-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://127.0.0.1:65535
