<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Authorization.Contracts\Authorization.Contracts.csproj" />
      <ProjectReference Include="..\Receipts.Contracts\Receipts.Contracts.csproj" />
      <ProjectReference Include="..\Fns.Contracts\Fns.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mediator.Abstractions" />
      <PackageReference Include="Rebus" />
    </ItemGroup>

</Project>
