<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Mediator.Abstractions" />
      <PackageReference Include="WTorricos.Results" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared.Utils\Shared.Utils.csproj" />
    </ItemGroup>

</Project>
