<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Refit" />
        <PackageReference Include="Refit.HttpClientFactory" />
        <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fns.Contracts\Fns.Contracts.csproj" />
      <ProjectReference Include="..\Shared.Utils\Shared.Utils.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ReceiptData\Mapper\" />
    </ItemGroup>

</Project>
