name: Build and push to Container registry

on: 
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NEt
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.304'
  
      - name: Restore dependencies
        run: dotnet restore

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: docker compose build

      - name: Push Docker images to GHCR
        run: docker compose push
        
      - name: Copy files to server 
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yaml, .env"
          target: "C:\\Users\\${{ secrets.SSH_USER }}\\RiderProjects\\HomeAccounting"
      - name: Deploy to Windows Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ./RiderProjects/HomeAccounting 
            docker compose pull
            docker compose down
            docker compose up
            
          
