name: Build and push to Container registry

on: 
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NEt
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.304'
  
      - name: Restore dependencies
        run: dotnet restore

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: docker compose build

      - name: Push Docker images to GHCR
        run: docker compose push
        
      - name: Copy files to server 
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yaml, .env"
          target: "C:\\Users\\${{ secrets.SSH_USER }}\\RiderProjects\\HomeAccounting"
      - name: Docker Compose Deployment (SSH)
  # You may pin to the exact commit or the version.
  # uses: humbertocrispim/ssh-docker-compose-action@1f8a21e589697bd9ba348a7b49cd3252d6181af5
        uses: humbertocrispim/ssh-docker-compose-action@v1.0.0
        with:
    # Private SSH key used for logging into remote system.
          ssh_private_key: ${{ secrets.SSH_KEY }}
    # Remote host name.
          ssh_host: ${{ secrets.SSH_HOST }}
    # Remote SSH port.
          ssh_port:  ${{ secrets.SSH_PORT }}
    # Remote user name.
          ssh_user:  ${{ secrets.SSH_USER }}
    # Docker Compose pull images.
          pull: true
          
